### ISSUE TITLE
调用diopiTensorCopyFromBuffer完成h2d操作

### ISSUE THREAD

**Issue by Aaron20000101** [DeepLink-org/DIOPI#290]
**现状**
目前diopi_test 中D2H的过程，是通过调用diopiTensorCopyToBuffer()完成d2h的传递。这个函数里面提供了tensor的指针，同时它是一个弱符号。所以厂商可以重写该函数，并根据tensor信息和硬件特性，在数据复制过程中，进行高效的数据类型和内存布局的转换。

而H2D的过程则不同，是在Tensor的构造函数里，直接调用了device_memcpy_h2d_async，以线性内存的方式复制到device里。 
**期望**
希望H2D能和D2H过程类似，调用diopiTensorCopyFromBuffer这个函数。厂商可以重写该函数，来解决H2D过程中数据类型和内存布局转换的问题。

**Comment by yewentao256** [comment]
你好，现在已经有`diopiTensorCopyFromBuffer`这个函数了，它的实现位于`dipu/third_party/DIOPI/diopi_test/csrc/litert.cpp`路径下，你期望的是在`diopiTensor`的构造函数里调用`diopiTensorCopyFromBuffer`包装而不是直接进行`device_memcpy_h2d_async`调用吗？

**Comment by Aaron20000101** [comment]
对
