### ISSUE TITLE
ctc_loss适配

### ISSUE THREAD

**Issue by MiaoYYu** [DeepLink-org/DIOPI#301]
pytorch逻辑和cnnlCTCLoss逻辑差异，导致在不修改pytroch的前提下，反向计算的适配出现问题。
log_alpha不影响前向计算的过程及结果，但是会影响反向计算的逻辑。cnnlCTCLoss在计算反向梯度时所需的reduction参数不能从对接的pytroch接口得到。[CTCLoss问题总结](https://aicarrier.feishu.cn/wiki/HEQpw4LVmioMUhkGG6lcbEmlnzg)

**Comment by PetrelYy** [comment]
嗯，后续若 DIOPI 集成 MLU-OPS，建议在MLU-OPS 重新开发接口完全对齐的算子。 
这个方案比较能行得通

**Comment by hellobuilder** [comment]
实验：可基于dipu注册机制（需要注意通用型），使用backward接口进行处理

**Comment by jingguo-st** [comment]
fixed in v0.2.6: registered a user defined backward function in dipu.
