### ISSUE TITLE
Copy kernel性能较慢

### ISSUE THREAD

**Issue by MiaoYYu** [DeepLink-org/DIOPI#302]
Copy kernel性能较慢
同contiguous输入比transpose慢一百倍
![image](https://github.com/DeepLink-org/DIOPI/assets/30998166/f68bee40-9066-4a22-9f64-c072c71f7c4f)
![image](https://github.com/DeepLink-org/DIOPI/assets/30998166/1a396b40-7dab-4178-aa47-d53dc3351d0a)

**Comment by PetrelYy** [comment]
@yewentao256 反馈case ，contiguous->non-contiguous，这类不连续IO copy没做优化，属于正常情况

**Comment by yewentao256** [comment]
好的，之后这类contiguous转contiguous的情况，我们会对寒武纪case做单独处理，优先调用transpose解决
