### ISSUE TITLE
Index put kernel bug 和 overflow问题

### ISSUE THREAD

**Issue by MiaoYYu** [DeepLink-org/DIOPI#303]
1. Index put kernel bug（accumulate为true且indices为bool），预期什么时候修好呢。
2. 还有一个是overflow问题：在370上是一个随机数
- When accumulate = true and the data type of input is int32, int16, int8 or uint8, the accumation result supports overflow on MLU500 series(excluding tp_520) and higher platforms; on the platforms earlier than MLU500 series, the overflow is not supported and undefined behaviour may occur if the overflow arises.

**Comment by PetrelYy** [comment]
1. 已合入 cnnl v1.20.0，8月底版本SDK会带上
2. 需要确认torch该行为是怎样？

**Comment by yewentao256** [comment]
1. 收到，时间符合预期
2. 软件栈升级后，目前测试overflow无法复现
