### ISSUE TITLE
为了解决fcos算子问题而更改为MMCV mlu 算子适配方式是否合适？

### ISSUE THREAD

**Issue by MiaoYYu** [DeepLink-org/DIOPI#305]
为了解决fcos算子问题而更改为MMCV mlu 算子适配方式是否合适？
  1. mmcv的fcos算子无问题，diopi有问题
  2. 短期不建议更改为MMCV mlu 算子适配方式
  3. 短期建议寒武纪支援解决此算子问题
  4. 长期MMCV mlu 算子适配方式建议加入排期

**Comment by PetrelYy** [comment]
正在与 @CokeDong  沟通定位中

**Comment by PetrelYy** [comment]
08.08 提供调试方式 & 调试代码， @CokeDong  是否已定位问题？

**Comment by PetrelYy** [comment]
问题根因：DIOPI 适配时未对focal_loss_sigmoid_forward 输入tensor target 进行转数（int64_t->int32_t），展开:

-  MMCV中 mlu 算子注册时使用到了 catch 中的功能，catch 默认将 buffer中 int64_t 数据转换为 int32_t
- DIOPI 需修改 focal_loss 适配代码，申请 mlu buffer时，对long类型做转数。 建议copy MLU-OPS中算子源码（host侧防呆完善，能及时发现该类问题）
