### ISSUE TITLE
Dangerous warnings in C++ codes

### ISSUE THREAD

**Issue by lljbash** [DeepLink-org/DIOPI#369]
**Describe the bug**
Too many dangerous warnings like `no return statement` / `may be used uninitialized` / `control sequence reaches the end`...

**To Reproduce**
```
$ cd impl; bash scripts/build_impl.sh torch
```

**Expected behavior**
No warnings during compilation.

Better add `-Werror` to compile options.

**Comment by yewentao256** [comment]
https://github.com/DeepLink-org/DIOPI/pull/427

Thanks for your suggestions, I've fixed the warning issues in this pr before.
