### ISSUE TITLE
[New op] sup  SyncBatchnorm in mlu

### ISSUE THREAD

**Issue by PetrelYy** [DeepLink-org/DIOPI#380]
适配算子  SyncBatchnorm，在370M8完成功能验证 & 入库
SyncBatchnorm 包含以下cnnl接口：

- 9.296. SyncBatchnormBackwardReduce
- 9.297. SyncBatchNormElemt
- 9.298. SyncBatchNormBackwardElemt
- 9.299. SyncBatchNormBackwardElemtV2
- 9.300. SyncBatchNormGatherStatsWithCounts
- 9.301. SyncBatchNormStats

参考文档见 
- https://www.cambricon.com/docs/sdk_1.13.0/cambricon_cnnl_1.19.1/user_guide/index.html
- https://www.cambricon.com/docs/sdk_1.13.0/cambricon_cnnl_1.19.1/developer_guide/cnnl_api/api/syncbatchnormbackwardelemt.html#cnnlsyncbatchnormbackwardelemt

**Comment by Bonbon-Tang** [comment]
https://github.com/DeepLink-org/DIOPI/pull/410

**Comment by Bonbon-Tang** [comment]
counts这个函数存在torch-cnnl输入不一致的问题，其余函数测试通过

**Comment by PetrelYy** [comment]
SyncBatchnormBackwardReduce
SyncBatchNormElemt
SyncBatchNormBackwardElemt
SyncBatchNormBackwardElemtV2
SyncBatchNormStats
 
已随 https://github.com/DeepLink-org/DIOPI/pull/410 合入，剩余SyncBatchNormGatherStatsWithCounts 后续单开PR合入

**Comment by Bonbon-Tang** [comment]
SyncBatchNormGatherStatsWithCounts 完成，和torch在counts negative时计算结果完全不同，因此加入了positive限制

**Comment by Bonbon-Tang** [comment]
所有函数均以完成
9.296. SyncBatchnormBackwardReduce
9.297. SyncBatchNormElemt
9.298. SyncBatchNormBackwardElemt
9.299. SyncBatchNormBackwardElemtV2
9.300. SyncBatchNormGatherStatsWithCounts
9.301. SyncBatchNormStats
