### ISSUE TITLE
无法跑通quick start例子

### ISSUE THREAD

**Issue by Kevin-XiongC** [DeepLink-org/DIOPI#490]
**Describe the bug**
``` bash
cd impl && sh scripts/build_impl.sh torch
```
即编译torch的算子库，编译完成后，生成了以下动态库
/home/xiongchao/work/DIOPI/impl/lib
├── export_functions.cpython-39-x86_64-linux-gnu.so
├── export_runtime.cpython-39-x86_64-linux-gnu.so
├── libdiopi_impl.so
└── libdiopirt.so
测试python脚本里import的为export_functions.cpython-39-x86_64-linux-gnu.so，
通过以下make过程的log中可知，算子实现放在libdiopi_impl.so中的
![image](https://github.com/DeepLink-org/DIOPI/assets/22584786/2d190cd7-9b4c-4b32-af4d-f21ae159d3b2)
可我通过readelf -d 其他三个so没有看到对libdiopi_impl的依赖

**Environment information**
cuda 11.8
torch2.0.0 (conda安装)
gcc9.4
DIOPI commit id 6f6da63ae86536008e347c2cb3dcfd88cb59de34
**Screenshots**
测试时，就一直报not implenmented.
``` bash
python main.py --mode run_test --fname relu
2023-10-17 16:16:25,460 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:25,462 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:25,465 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:25,465 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:25,918 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:26,234 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:26,266 - ConformanceTest - ERROR - NotImplemented: relu not implement
2023-10-17 16:16:26,272 - ConformanceTest - ERROR - NotImplemented: relu not implement
```
在python侧运行其他api，也不正常。
![image](https://github.com/DeepLink-org/DIOPI/assets/22584786/7a566009-8e7a-4f85-bcc1-fce405ed19ae)

我理解理论上应该得有对libdiopi_impl.so依赖？谢谢解答

**Comment by wey-code** [comment]
Hello， @Kevin-XiongC，事实上其余的三个so都是依赖于libdiopi_impl。我尝试了我手上的cuda 11.7，torch2.0.0，gcc9.4， DIOPI commit id https://github.com/DeepLink-org/DIOPI/commit/6f6da63ae86536008e347c2cb3dcfd88cb59de34 配置，并没有复现问题。三个都链接到了diopi_impl。所以麻烦再double check一下是否编译过程中出错了？或者提供编译过程的日志以及so文件的动态段信息帮助我们具体排查。
![image](https://github.com/DeepLink-org/DIOPI/assets/60810292/32209863-ca36-4c89-8834-4e9d4f7ed863)
![image](https://github.com/DeepLink-org/DIOPI/assets/60810292/b67d7e4e-d6fd-4178-ab1a-94ee208c8b70)
![image](https://github.com/DeepLink-org/DIOPI/assets/60810292/68efa0be-9b1a-4e28-badb-905b6ec15847)
另外我猜测一个可能的原因是diopi_impl里都是弱符号，编译器在优化时可能会优化掉而放弃链接，可以尝试一下将https://github.com/DeepLink-org/DIOPI/blob/6f6da63ae86536008e347c2cb3dcfd88cb59de34/impl/torch/test/CMakeLists.txt#L43 更换为：
`target_link_libraries(${DIOPIFUNCTIONS} PRIVATE diopirt -Wl,--no-as-needed ${DEVICEIMPL} -Wl,--as-needed)`
如果有什么进展请与我联系~ 
祝好~

**Comment by Kevin-XiongC** [comment]
> Hello， @Kevin-XiongC，事实上其余的三个so都是依赖于libdiopi_impl。我尝试了我手上的cuda 11.7，torch2.0.0，gcc9.4， DIOPI commit id [6f6da63](https://github.com/DeepLink-org/DIOPI/commit/6f6da63ae86536008e347c2cb3dcfd88cb59de34) 配置，并没有复现问题。三个都链接到了diopi_impl。所以麻烦再double check一下是否编译过程中出错了？或者提供更详细的配置信息（如cmake版本）、编译过程的日志以及so文件的动态段信息帮助我们具体排查。 ![image](https://user-images.githubusercontent.com/60810292/277648890-32209863-ca36-4c89-8834-4e9d4f7ed863.png) ![image](https://user-images.githubusercontent.com/60810292/277649262-b67d7e4e-d6fd-4178-ab1a-94ee208c8b70.png) ![image](https://user-images.githubusercontent.com/60810292/277649334-68efa0be-9b1a-4e28-badb-905b6ec15847.png) 另外我猜测一个可能的原因是diopi_impl里都是弱符号，编译器在优化时可能会优化掉而放弃链接(虽然我在gcc9.4上并未复现这一问题)，可以尝试一下将
> 
> https://github.com/DeepLink-org/DIOPI/blob/6f6da63ae86536008e347c2cb3dcfd88cb59de34/impl/torch/test/CMakeLists.txt#L43
> 
> 更换为：
> ```c++
> target_link_libraries(${DIOPIFUNCTIONS} PRIVATE diopirt -Wl,--no-as-needed ${DEVICEIMPL} -Wl,--as-needed)
> ```
> 
> 如果有什么进展请与我联系~ 祝好~

Hi, 经排查为弱符号的问题，编译器选择了不链接，thx~
